package com.autoapply.formautomation.dto;

import java.util.List;
import java.util.Map;

/**
 * DTO representing the automation plan generated by AI analysis.
 */
public class AutomationPlanDTO {
    private String pageType; // job_application, job_listing, profile_page, etc.
    private Boolean isApplicationForm;
    private List<AutomationActionDTO> actions;
    private Map<String, String> fieldMappings; // Maps profile fields to form fields
    private String confidence; // HIGH, MEDIUM, LOW
    private List<String> warnings; // Warnings about fields that couldn't be mapped
    private List<String> suggestions; // Suggestions for user interaction
    private String jobTitle;
    private String companyName;

    public AutomationPlanDTO() {}

    public String getPageType() {
        return pageType;
    }

    public void setPageType(String pageType) {
        this.pageType = pageType;
    }

    public Boolean getIsApplicationForm() {
        return isApplicationForm;
    }

    public void setIsApplicationForm(Boolean isApplicationForm) {
        this.isApplicationForm = isApplicationForm;
    }

    public List<AutomationActionDTO> getActions() {
        return actions;
    }

    public void setActions(List<AutomationActionDTO> actions) {
        this.actions = actions;
    }

    public Map<String, String> getFieldMappings() {
        return fieldMappings;
    }

    public void setFieldMappings(Map<String, String> fieldMappings) {
        this.fieldMappings = fieldMappings;
    }

    public String getConfidence() {
        return confidence;
    }

    public void setConfidence(String confidence) {
        this.confidence = confidence;
    }

    public List<String> getWarnings() {
        return warnings;
    }

    public void setWarnings(List<String> warnings) {
        this.warnings = warnings;
    }

    public List<String> getSuggestions() {
        return suggestions;
    }

    public void setSuggestions(List<String> suggestions) {
        this.suggestions = suggestions;
    }

    public String getJobTitle() {
        return jobTitle;
    }

    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
}

